version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quartz_app
    ports:
      - "5000:80"
    networks:
      - app_network

networks:
  app_network:
